### ISSUE TITLE
Customize Colors for Syntax Highlighting

### ISSUE THREAD

**Issue by 8** [madskristensen/OpenCommandLine#47]
Hi Mads,

first I'd like to thank you for this extension (and all your other extensions, I think I am running 8 of them)!

I am using Visual Studio 2015 and I'd like to ask if there is an option to customize the colors that are used for highlighting. In particular, I would like to change the color of the comment to a brighter one. I've noticed, that it does not pick up the color I've specified under Tools -> Options -> Fonts and Colors -> Comment.

I've looked for an extension specific setting like "OpenCommandLine Comment" or something like that, but didn't find any (the whole Fonts and Colors dialog is rather messy)

I've taken a quick look into the source code and didn't find any hard coded colors - CmdClassifier.cs seems only to mark it as an PredefinedClassificationTypeNames.Comment. I would have guessed that Visual Studio would then use the Color setting for the default comment then, but that's not the case for me.

Do you have any pointers?

Take care,
Martin

**Comment by madskristensen** [comment]
I've removed the syntax highlighting since VS2015 now supports Textmate bundles and VSl2017 ships with one for .cmd and .bat files. For VS2015 you should get the [Syntax Highlighter Pack](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.SyntaxHighlightingPack)

That will fix the issue
