### ISSUE TITLE
Several PowerShell features disabled when launched from Open Command Line

### ISSUE THREAD

**Issue by stamminator** [madskristensen/OpenCommandLine#67]
When a PowerShell console is launched using this extension (whether with `Shift`+`Alt`+`.`, with `Alt`+`Space` as the default, or with the context menu, it makes no difference), several of PowerShell's standard editing features do not work, such as syntax highlighting and hotkey commands like `Ctrl`+`X`. If I launch a PowerShell window manually to the same directive that OCL opens it to, all functionality is normal.

Here are my extension settings. Changing it to use no command arguments makes no difference.

![ocl settings](https://user-images.githubusercontent.com/10633170/41260680-6efdefa0-6da6-11e8-8c2d-5f33b2f6ad51.jpg)

Here are some captures comparing the manually-launched console (left) and the OCL-launched console (right) and their different behaviors.

### Ctrl+Z (undo)
![crtl z comparison](https://user-images.githubusercontent.com/10633170/41260707-97bb9ab4-6da6-11e8-83c5-ced54cca6b72.GIF)

### Syntax highlighting
![syntax highlighting comparison](https://user-images.githubusercontent.com/10633170/41260782-e2cb6e30-6da6-11e8-9ea0-c6c35edbf9af.jpg)

### Ctrl+A, Backspace to delete entire line
![ctrl a backspace comparison](https://user-images.githubusercontent.com/10633170/41260870-4080d2a4-6da7-11e8-8c27-3262c0aa7dad.GIF)

### Multi-line commands
![multi-line command comparison](https://user-images.githubusercontent.com/10633170/41261023-ec448a4a-6da7-11e8-8366-3896225085ee.GIF)

Any idea what could be causing this?

**Comment by dubeg** [comment]
Alright, so, PSReadline, which is installed & imported by default on Windows 10, isn't loaded when Powershell is started from Visual Studio. 

_PsReadline is a module that provides rich editing features in the command line, so not having it loaded is probably the problem here._

Visual Studio runs as a 32-bit process, and so when Powershell is launched from this extension with the path `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`, the actual path being used is `C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe`, which points to the 32-bit version of Powershell. 

I said previously that this module is installed by default on Windows 10. The problem is that it's only installed in `C:\Program Files\WindowsPowerShell\Modules`; it's not in `C:\Program Files (x86)\WindowsPowerShell\Modules`. So there's the problem. I don't know why it's not in (x86): is it that PsReadline isn't suited for 32-bit, or is it merely an oversight?

Anyway, the quick fix is to set this special path in the settings, which will launch 64-bit Powershell if you're on 64-bit Windows, as expected:

```
C:\WINDOWS\sysnative\WindowsPowerShell\v1.0\powershell.exe
```

![image](https://user-images.githubusercontent.com/6020602/42768765-5a8b0360-88ee-11e8-85f2-328cb05dec73.png)

**Comment by stamminator** [comment]
Thanks, this resolved it.
